### ISSUE TITLE
TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by verhulstd** [Charlicus/react-semantic-datetime#1]
After implementing your component the following error occurs:
TypeError: Cannot read property 'format' of undefined

**Comment by Charlicus** [comment]
Hello @verhulstd , thank you for your interest, Could share your component's code in order to help me identifying the problem ?

**Comment by Charlicus** [comment]
@verhulstd , I have been able to reproduce the error and solved the issue.

One of the state value was not yet set in the first render,  it should work now, let me know !

Please use version 1.0.3
