### ISSUE TITLE
Select a day and load another

### ISSUE THREAD

**Issue by kevinpiske** [Charlicus/react-semantic-datetime#2]
When you select a date, the component is loading another.
This problem occurs in your demo gif. See that you select April 7, 2016 but are loading April 13, 2016.

**Comment by Charlicus** [comment]
Thank you for your testing, I'll investigate and correct asap

**Comment by Charlicus** [comment]
Hello @kevinpiske , the error should have been solved in the last deployment. Again thks again for the testing !
